#!/usr/bin/env python3
"""
DiscoverAI: Create the product_review_summaries table (AI Review Summary)
=============================================================================

Schema for the AI-generated review summary feature (discussed and scoped
before building - see review_summary_routes.py for the full design
writeup). One row per product, with separate draft/published text so a
moderator can generate or edit a new draft WITHOUT changing what's
currently live on the PDP, then explicitly publish when ready:

  - draft_text            - latest generated (or manually edited) text,
                             not yet necessarily shown to customers.
  - published_text        - what's actually live on the PDP right now.
                             NULL until the first Publish.
  - review_count_at_generation - how many approved, written reviews existed
                             when draft_text was last (re)generated -
                             lets the admin UI flag "N new reviews since
                             this was generated" without a live recount.
  - is_edited              - true once a moderator has hand-edited
                             draft_text since it was last (re)generated by
                             the model - so a future regenerate can warn
                             "this will overwrite your edits" instead of
                             silently clobbering them.
  - generated_at / published_at - timestamps for each side.

Eligibility (>=5 approved reviews WITH text) is enforced in
review_summary_routes.py at generation time, not by this schema - a
product can have a summaries row before or after crossing that
threshold, the row itself doesn't encode eligibility.

Idempotent: CREATE TABLE IF NOT EXISTS, safe to re-run.

Usage:
    python CREATE_REVIEW_SUMMARIES_TABLE.py            # dry run - shows the plan, writes nothing
    python CREATE_REVIEW_SUMMARIES_TABLE.py --apply    # creates the table
"""

import os
import sys

CREATE_TABLE_SQL = """
    CREATE TABLE IF NOT EXISTS product_review_summaries (
        id character varying(50) PRIMARY KEY,
        product_id character varying(50) NOT NULL UNIQUE REFERENCES products(id),
        draft_text text,
        published_text text,
        review_count_at_generation integer,
        is_edited boolean NOT NULL DEFAULT false,
        generated_at timestamp without time zone,
        published_at timestamp without time zone,
        created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
    );
"""


def main():
    apply_changes = "--apply" in sys.argv

    print("Plan:")
    print("  CREATE TABLE IF NOT EXISTS product_review_summaries (...)")
    print("    - one row per product_id (UNIQUE)")
    print("    - draft_text / published_text kept separate (draft-then-publish workflow)")
    print("    - review_count_at_generation, is_edited (staleness/edit tracking)")

    if not apply_changes:
        print("\n(dry run - nothing written. Re-run with --apply to create the table.)")
        return

    import psycopg2
    from dotenv import load_dotenv

    load_dotenv()
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        print("ERROR: DATABASE_URL not set.")
        sys.exit(1)

    print("\nConnecting to Neon...")
    conn = psycopg2.connect(database_url)
    cur = conn.cursor()
    print("Connected.")

    cur.execute(CREATE_TABLE_SQL)
    conn.commit()

    print("\nDone. product_review_summaries table is ready.")

    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
